addSbtPlugin("com.dwijnand"       % "sbt-dynver"               % "3.3.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.9.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.26")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"             % "1.6.0-RC4")
